- hosts: all
  tasks:
    - name: Install ~/.ssh/authorized_keys
      when: 0>1
      ansible.posix.authorized_key:
        user: "{{ lookup('env', 'USER') }}"
        state: present
        key: >
          {{ lookup('url', 'https://github.com/gbenson.keys') }}
          {{ lookup('env', 'USER') }}@inauspicious.org

    - name: Install packages
      become: yes
      ansible.builtin.apt:
        pkg:
        - emacs-gtk
        - git
        - openssh-server
        - python3-venv
        - yaml-mode
