---
- hosts: all
  vars:
    dpkg_architecture: "amd64"  # XXX $(dpkg --print-architecture)
    docker_repo_url: "https://download.docker.com/linux/ubuntu"
    docker_keyring_path: "/etc/apt/trusted.gpg.d/docker-keyring.asc"
    docker_sources_path: "/etc/apt/sources.list.d/docker.list"
    google_keyring_path: "/etc/apt/trusted.gpg.d/google-keyring.asc"
    cache_dir: ~/.cache/gbenson/ansible-machine-setup
    fonts_dir: ~/.local/share/fonts
    tic80_desktop_file: /usr/local/share/applications/tic80.desktop

  tasks:
    #- debug:
    #    var: ansible_facts

    - name: Install ~/.ssh/authorized_keys
      ansible.posix.authorized_key:
        user: "{{ lookup('env', 'USER') }}"
        state: present
        key: >
          {{ lookup('url',
          'https://github.com/gbenson.keys',
          split_lines=False) }}

    - name: Uninstall problem packages
      become: yes
      ansible.builtin.apt:
        name: docker.io
        state: absent
      when: ansible_facts["distribution"] == "Ubuntu"
      # XXX or "os_family": "Debian",
      # XXX or "pkg_mgr": "apt",

    - name: Add Docker package signing key
      become: yes
      ansible.builtin.get_url:
        url: "{{ docker_repo_url }}/gpg"
        dest: "{{ docker_keyring_path }}"
      when: ansible_facts["distribution"] == "Ubuntu"

    - name: Add Docker CE APT repository
      become: yes
      ansible.builtin.apt_repository:
        repo: >
          deb [arch={{ dpkg_architecture }}
          signed-by={{ docker_keyring_path }}]
          {{ docker_repo_url }}
          {{ ansible_distribution_release }}
          stable
        state: present
        filename: docker
      when: ansible_facts["distribution"] == "Ubuntu"

    - name: Install Docker
      become: yes
      ansible.builtin.apt:
        pkg:
          - docker-ce
          - docker-compose-plugin
      when: ansible_facts["distribution"] == "Ubuntu"

    - name: Add Chrome package signing key
      become: yes
      ansible.builtin.get_url:
        url: https://dl.google.com/linux/linux_signing_key.pub
        dest: "{{ google_keyring_path }}"
      when: ansible_facts["distribution"] == "Ubuntu"

    - name: Add Chrome APT repository
      become: yes
      ansible.builtin.apt_repository:
        repo: >
          deb [arch={{ dpkg_architecture }}
          signed-by={{ google_keyring_path }}]
          https://dl.google.com/linux/chrome/deb/
          stable main
        state: present
        filename: google-chrome
      when: ansible_facts["distribution"] == "Ubuntu"

    - name: Install Chrome
      become: yes
      ansible.builtin.apt:
        name: google-chrome-stable
      when: ansible_facts["distribution"] == "Ubuntu"

    - name: Install packages
      become: yes
      ansible.builtin.apt:
        pkg:
          - curl
          - emacs-gtk
          - git
          - hydra
          - openssh-server
          - nmap
          - python2
          - python3-dev
          - python3-venv
          - yaml-mode
      when: ansible_facts["os_family"] == "Debian"

    - name: Install Ubuntu-specific packages
      become: yes
      ansible.builtin.apt:
        pkg:
          - apport-retrace
          - gnome-tweaks
      when: ansible_facts["distribution"] == "Ubuntu"

    - name: Configure git
      ansible.builtin.copy:
        src: dotfiles/gitconfig
        dest: ~/.gitconfig
        mode: "0644"
        backup: yes

    - name: Configure Docker
      become: yes
      ansible.builtin.user:
        name: "{{ lookup('env', 'USER') }}"
        groups: docker
        append: yes

    - name: Configure Emacs
      ansible.builtin.git:
        repo: git@github.com:gbenson/emacs-config.git
        dest: ~/.emacs.config

    - name: Install ~/.emacs
      ansible.builtin.file:
        src: .emacs.config/dot.emacs
        dest: ~/.emacs
        state: link

    - name: Configure GDB+debuginfod
      block:
        - name: Export DEBUGINFOD_URLS
          ansible.builtin.lineinfile:
            path: ~/.profile
            line: export DEBUGINFOD_URLS="https://debuginfod.ubuntu.com"

        - name: Enable debuginfod in ~/.gdbinit
          ansible.builtin.lineinfile:
            path: ~/.gdbinit
            line: set debuginfod enabled on
            create: yes
      when: ansible_facts["distribution"] == "Ubuntu"

    - name: Enable core deb-src repos
      become: yes
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list
        regexp: ^# (deb-src .* {{ item }} main restricted)$
        line: \g<1>
        backrefs: yes
      loop:
        - "{{ ansible_distribution_release }}"
        - "{{ ansible_distribution_release }}-updates"
        - "{{ ansible_distribution_release }}-security"
      when: ansible_facts["distribution"] == "Ubuntu"

    - name: Check if Lexend font exists
      ansible.builtin.stat:
        path: "{{ fonts_dir }}/Lexend-VariableFont_wght.ttf"
      register: lexend_ttf

    - block:
        - name: Ensure cache directory exists
          ansible.builtin.file:
            path: "{{ cache_dir }}"
            state: directory
            mode: "0700"

        - name: Download Lexend
          ansible.builtin.get_url:
            url: https://fonts.google.com/download?family=Lexend
            dest: "{{ cache_dir }}/lexend.zip"

        - name: Ensure fonts directory exists
          ansible.builtin.file:
            path: "{{ fonts_dir }}"
            state: directory
            mode: "0755"

        - name: Extract Lexend variable-weight font
          ansible.builtin.unarchive:
            src: "{{ cache_dir }}/lexend.zip"
            dest: "{{ fonts_dir }}"
            include: Lexend-VariableFont_wght.ttf
      when: >
        ansible_facts["distribution"] == "Ubuntu"
        and not lexend_ttf.stat.exists

    - name: Install TIC-80 build requirements
      become: yes
      ansible.builtin.apt:
        pkg:
          - cmake
          - freeglut3-dev
          - g++
          - libasound2-dev
          - libglu1-mesa-dev
          - libglvnd-dev
          - ruby-full
      when: ansible_facts["nodename"] == "molly"

    - name: Check whether TIC-80 is installed
      ansible.builtin.stat:
        path: "{{ tic80_desktop_file }}"
      register: tic80_desktop

    - name: Make TIC-80 fullscreen by default
      become: yes
      ansible.builtin.lineinfile:
        path: "{{ tic80_desktop_file }}"
        regexp: ^Exec=
        line: Exec=tic80 --fullscreen %U
      when: tic80_desktop.stat.exists
